# This is the default configuration file for the project. This configuration is
# used in any environment unless specifically overridden.
# DO NOT CHANGE THIS FILE. Instead create a new configuration file that holds
# the overwrites as explained in https://www.npmjs.com/package/config.

app:
  name:
    machine: 'contentajs'
    human-readable: 'ContentaJS'
  # The port for the server to listen on.
  port: 3000

  # The number of child processes to start. The total number of processes will be
  # split between web workers. 0 will instruct the application to use the maximum
  # number of processors available on the machine.
  processes: 0
  adiosSocket: ./adios.sock

cms:
  # Add the URL including the protocol to your Contenta CMS installation.
  # Example: https://www.example.com
  host: http://localhost

applicationCache:
  activePlugin: redis
  plugins:
    redis:
      # Add the URL including the protocol to your Redis node or Cluster using the
      # "redis" scheme name (https://www.iana.org/assignments/uri-schemes/prov/redis).
      # Example: redis://:authpassword@127.0.0.1:6380/4 (Connect to 127.0.0.1:6380,
      # db 4, using password "authpassword")
      host: redis://127.0.0.1:6379
      # Additional options for ioredis https://www.npmjs.com/package/ioredis passed
      # verbatim.
      options:
        scaleReads: 'slave'
      # Configuration about the connection pool using generic-pool. The options are
      # passed verbatim to the pool. These defaults are very generic, you should
      # take the time to tune it for your traffic.
      pool:
        # Limit the connection pool to the specified number of sockets.
        max: 30
        autostart: true
        testOnBorrow: true

# These settings will determine the TTL for edge cache.
cache:
  max-age:
    # Cache OPTIONS responses for one day.
    OPTIONS: 86400
    # The value to use for all GET requests unless otherwise specified.
    default: 900
    # Add sub-routes here to override the defaults
    # articles: 420
    # node--volatiles: 60

timeout:
  # Time in milliseconds before worker processes are forcefully killed when the
  # master process receives a SIGINT.
  killTimeout: 10000
  # The time in milliseconds to allow before a request is considered timed out
  # and the client connection severed. Timeouts can be per version and per entity
  # type.
  requestTimeout:
    default: 12000
    defaultListing: 12000
  # The time in milliseconds to set the retry-after header value to in the event
  # of a request timeout.
  retryAfter: 1200

cors:
  origin:
    default: http://localhost:3000
    whitelisted:
      - http://localhost:3000
      - https://localhost:3443
  headers:
    - 'Accept'
    - 'Authorization'
    - 'Cache-Control'
    - 'Content-Length'
    - 'Content-Type'
    - 'Keep-Alive'
    - 'Origin'
    - 'User-Agent'
    - 'X-Forwarded-For'
    - 'X-Forwarded-Port'
    - 'X-Forwarded-Proto'
    - 'X-HTTP-Method-Override'
    - 'X-Requested-With'

subrequests:
  # The path where the request aggregator lives.
  path: /subrequests
  # You can set this to 'multipart' as well.
  responseMerger: json
